version: 2
checkout:
    post:
      - mkdir -p /home/circleci/tutor/backend/logs
      - touch /home/circleci/tutor/backend/logs/app.log
jobs:

  build:
    working_directory: ~/tutor
    docker:
      - image: circleci/node:10.0.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: npm run coverage
